version: "3.9"

services:
  dr_preheat:
    build: .
    container_name: dr_preheat
    environment:
      NEVIWEB_USERNAME: ${NEVIWEB_USERNAME}
      NEVIWEB_PASSWORD: ${NEVIWEB_PASSWORD}

    restart: always